[agent]
  interval = "60s"
  round_interval = true
  flush_interval = "15s"
  omit_hostname = true

[[inputs.vsphere]]
  vcenters = ["${VSPHERE_URL}"]
  username = "${VSPHERE_USERNAME}"
  password = "${VSPHERE_PASSWORD}"
  insecure_skip_verify = ${VSPHERE_INSECURE_SKIP_VERIFY}
  force_discover_on_init = true

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
  path = "/metrics"
